export const batch = {
  batchId: '20260903-cling-film-high-intent-97-126',
  articleDir: '工作流/文章/保鲜膜高转化30篇-97-126',
  scheduleStart: '2026-09-06',
  scheduleEnd: '2026-10-05',
  expectedArticles: 30,
  expectedImages: 30,
}

const sharedLinks = [
  '/products/commercial-cling-film-roll',
  '/documents',
  '/contact',
]

const officialSources = {
  103: [
    'https://www.fda.gov/food/packaging-food-contact-substances-fcs/food-types-conditions-use-food-contact-substances',
  ],
  114: [
    'https://www.fda.gov/food/packaging-food-contact-substances-fcs/determining-regulatory-status-components-food-contact-material',
  ],
  115: [
    'https://www.wcoomd.org/en/topics/nomenclature/instrument-and-tools/advance-rulings-for-classification.aspx',
    'https://www.help.cbp.gov/s/article/Article-1106?language=en_US',
    'https://hts.usitc.gov/',
  ],
  117: [
    'https://food.ec.europa.eu/food-safety/chemical-safety/food-contact-materials/legislation_en',
  ],
  120: [
    'https://library.iccwbo.org/content/clp/Others/incoterms_2020_checklist_2024-update.pdf',
  ],
  121: [
    'https://www.dhl.com/us-en/home/global-forwarding/products-and-solutions/ocean-freight/less-than-container-load.html',
  ],
  122: [
    'https://www.hapag-lloyd.com/en/services-information/cargo-fleet/container.html',
  ],
  125: [
    'https://food.ec.europa.eu/food-safety/chemical-safety/food-contact-materials/legislation_en',
    'https://www.fda.gov/food/packaging-food-contact-substances-fcs/determining-regulatory-status-components-food-contact-material',
  ],
  126: [
    'https://www.fda.gov/food/packaging-food-contact-substances-fcs/food-types-conditions-use-food-contact-substances',
    'https://www.fsai.ie/business-advice/running-a-food-business/caterers/cling-film-safety-of-use',
  ],
}

const rows = [
  [97, '2026-09-06', 'size-selection', '300mm (12-Inch) vs 450mm (18-Inch) Cling Film Rolls', '300mm-vs-450mm-commercial-cling-film-rolls', '300mm vs 450mm cling film', ['12 inch vs 18 inch plastic wrap', 'commercial cling film width'], 'commercial investigation', 'specification', 'Choose a roll width from actual pan, tray, dispenser, handling, and carton constraints.', 'Food-service distributors and multi-site kitchen buyers', 'cling-film-distributor-sku-assortment-width-length', 'Moves from portfolio planning to one exact width decision with a pan/dispenser measurement worksheet.', 'medium', 'Compare width choices with a measurement table and sample gate.', 'A procurement bench with 300 mm and 450 mm clear cling film rolls beside matching stainless food pans and dispensers.'],
  [98, '2026-09-07', 'size-selection', '100m, 300m, or 500m Cling Film Rolls: Choosing Order Length', '100m-300m-500m-cling-film-roll-length-selection', 'cling film roll length 100m 300m 500m', ['commercial cling film roll length', '300m vs 500m cling film'], 'commercial investigation', 'specification', 'Select roll length from usage rate, changeovers, dispenser capacity, lifting, and inventory.', 'Importers, restaurant suppliers, and private-label buyers', 'cling-film-roll-length-net-weight-verification', 'Selects the commercial length before ordering; the existing article verifies whether delivered length is accurate.', 'low', 'Provide a shift-usage and roll-change calculation rather than a generic size list.', 'Three clear food cling film rolls of visibly different diameters arranged with a kitchen dispenser and an inventory planning sheet.'],
  [99, '2026-09-08', 'thickness-selection', '8, 10, or 12 Micron Cling Film: How Buyers Choose a Starting Spec', '8-10-12-micron-cling-film-thickness-selection', '8 10 12 micron cling film', ['cling film thickness guide for buyers', 'commercial plastic wrap micron'], 'commercial investigation', 'specification', 'Choose a trial thickness from handling, tray geometry, film use, cost, and controlled sample results.', 'Cling-film importers and food-service distributors', 'cling-film-thickness-tolerance-measurement-buyer-guide', 'Chooses nominal thickness by application; the existing article defines measurement and tolerance approval after selection.', 'medium', 'Use a trial matrix that separates nominal micron from performance acceptance.', 'A quality bench showing three clear cling film rolls labeled only by neutral color dots, with a micrometer and food trays; no readable text.'],
  [100, '2026-09-09', 'format-selection', 'Cutter Box vs Refill Roll Cling Film: Cost, Labor, and Storage', 'cutter-box-vs-refill-roll-cling-film-buying-guide', 'cutter box vs refill roll cling film', ['cling film refill roll wholesale', 'commercial plastic wrap cutter box'], 'commercial investigation', 'format', 'Choose between a complete cutter box and refill-roll supply model.', 'Food-service distributors, kitchens, and private-label buyers', 'cutter-box-cling-film-blade-box-roll-fit-checklist', 'Compares the two supply formats and total workflow; the existing article inspects quality within a chosen cutter-box format.', 'low', 'Quantify dispenser ownership, replacement rate, storage cube, labor, and packaging waste.', 'Side-by-side commercial cling film cutter box and unbranded refill roll on a stainless food-service prep counter.'],
  [101, '2026-09-10', 'equipment-fit', 'Hand-Wrap vs Automatic-Overwrap Food Film: Choose the Right Roll', 'hand-wrap-vs-automatic-overwrap-food-film', 'hand wrap vs automatic overwrap food film', ['manual food wrap film roll', 'automatic food overwrap film'], 'commercial investigation', 'equipment compatibility', 'Decide whether food film will be applied by hand, a dispenser, a tabletop overwrapper, or an automatic tray line.', 'Food processors, supermarket packers, and importers', 'food-cling-film-vs-pallet-stretch-film-rfq', 'Separates manual and equipment-run food overwrap without using the ambiguous hand-grade/machine-grade stretch-film terminology; the existing article separates food film from pallet film.', 'medium', 'Map application method, equipment inputs, and approval trials without promising universal compatibility.', 'A manual food wrapping station beside an automatic tray overwrapping line, each using a clear food film roll.'],
  [102, '2026-09-11', 'equipment-rfq', 'Cling Film for Automatic Tray Wrappers: An RFQ Compatibility Sheet', 'automatic-tray-wrapper-cling-film-rfq-checklist', 'cling film for automatic tray wrapping machine', ['food wrap film machine compatibility', 'tray overwrapper film roll specification'], 'transactional', 'RFQ', 'Collect the machine, roll, core, web, speed, tray, and trial fields needed for a supplier quote.', 'Supermarkets and food processors with tray wrapping equipment', 'cling-film-core-size-strength-dispenser-compatibility', 'Builds a complete machine-specific RFQ and line trial; the existing article focuses on core and dispenser fit.', 'medium', 'Deliver a copyable equipment compatibility brief and pass/fail line-trial record.', 'A clear cling film roll mounted on an automatic supermarket tray wrapping machine with blank control screen and no brand.'],
  [103, '2026-09-12', 'meat-overwrap', 'PVC Meat Overwrap Film: Specify Width, Gauge, Core, and Roll Length', 'pvc-meat-overwrap-film-roll-specification', 'PVC meat overwrap film', ['meat wrapping film roll wholesale', 'supermarket tray overwrap film supplier'], 'transactional', 'specification', 'Prepare a machine-ready PVC meat-overwrap specification without relying on vague high-cling claims.', 'Supermarket meat departments, processors, and distributors', 'cling-film-meat-deli-trays-cold-display-checks', 'Targets a roll/equipment purchase specification; the existing article tests cold-display behavior on wrapped trays.', 'high', 'Separate equipment fit, intended food/contact conditions, optical trial, handling trial, and evidence requests.', 'A supermarket meat tray wrapping workstation with a wide clear film roll, empty clean trays, and stainless equipment; no food close-up.'],
  [104, '2026-09-13', 'hotel-foodservice', 'Commercial Cling Film for Hotel Kitchens: A Multi-Station Buying Plan', 'commercial-cling-film-hotel-kitchen-buying-plan', 'commercial cling film for hotels', ['hotel kitchen plastic wrap wholesale', 'catering cling film supplier'], 'commercial investigation', 'use-case procurement', 'Plan widths, lengths, dispensers, case packs, storage, and replenishment across hotel kitchen stations.', 'Hotel groups, catering suppliers, and hospitality procurement teams', 'commercial-cling-film-rolls-restaurants-bulk-orders', 'Handles multi-station hotel demand, shared SKUs, issue control, and replenishment rather than a single restaurant product check.', 'low', 'Provide a station-by-station demand sheet and consolidation rule.', 'A professional hotel kitchen storeroom with organized clear cling film rolls assigned to several stainless prep stations.'],
  [105, '2026-09-14', 'bakery-foodservice', 'Cling Film for Bakeries: Select Rolls for Prep, Trays, and Display', 'cling-film-for-bakeries-roll-selection', 'cling film for bakeries', ['bakery plastic wrap wholesale', 'commercial food wrap for bakery trays'], 'commercial investigation', 'use-case procurement', 'Select roll format through dough prep, ingredient pans, trays, refrigeration, and display workflows.', 'Bakery chains, commissaries, and food-service distributors', 'food-service-cling-film-roll-guide', 'Uses bakery-specific surfaces, temperatures, tray sizes, handling and display checkpoints rather than a general food-service overview.', 'medium', 'Build a bakery trial route with clear exclusions for hot surfaces and unsupported claims.', 'A clean commercial bakery prep area with clear cling film covering ingredient pans and unbranded rolls near baking trays.'],
  [106, '2026-09-15', 'central-kitchen', 'Cling Film for Central Kitchens: Usage, Changeover, and Reorder Planning', 'cling-film-central-kitchen-usage-reorder-planning', 'cling film for central kitchens', ['meal prep cling film bulk rolls', 'commissary kitchen food wrap supplier'], 'commercial investigation', 'use-case procurement', 'Convert batch schedules, pan sizes, film use, roll changes, and waste into a reorder plan.', 'Central kitchens, meal-prep operators, and contract caterers', 'cling-film-trial-order-scorecard-reorder-decision', 'Creates demand and changeover inputs before purchasing; the existing scorecard decides whether to reorder after a trial.', 'low', 'Include a shift-level consumption worksheet and safety-stock calculation inputs without invented demand data.', 'A large central kitchen prep line with multiple stainless pans, clear film rolls, dispensers, and a neutral shift planning clipboard.'],
  [107, '2026-09-16', 'rfq-disambiguation', 'Food Cling Film vs Lidding Film: Send the Right Packaging RFQ', 'food-cling-film-vs-lidding-film-rfq', 'cling film vs lidding film', ['food wrap film vs tray lidding film', 'cling film or sealing film'], 'commercial investigation', 'RFQ qualification', 'Determine whether the buyer needs self-clinging overwrap or equipment-sealed lidding material.', 'Food brands, tray packers, and first-time packaging buyers', 'food-cling-film-vs-pallet-stretch-film-rfq', 'Prevents confusion with tray-sealing lidding film; the existing article prevents confusion with pallet stretch film.', 'medium', 'Use package geometry, equipment, seal method, roll format, and validation ownership as decision gates.', 'Two food packaging stations side by side: a hand-applied clear cling film roll and a tray-sealing lidding film machine.'],
  [108, '2026-09-17', 'rfq-disambiguation', 'Cling Film vs Shrink Film for Food Packaging: Buyer Decision Guide', 'cling-film-vs-shrink-film-food-packaging', 'cling film vs shrink film for food packaging', ['food wrap vs shrink wrap', 'cling film or heat shrink film'], 'commercial investigation', 'RFQ qualification', 'Separate cling/overwrap and heat-shrink processes before requesting material or equipment.', 'Importers and food-packaging project managers', 'food-cling-film-vs-pallet-stretch-film-rfq', 'Addresses heat-driven shrink equipment and package outcome; the existing article addresses pallet stabilization film.', 'medium', 'Provide a process-based decision tree and explicit equipment/use boundaries.', 'A clear cling film wrapping setup beside a separate heat-shrink packaging tunnel, clean industrial food packaging environment.'],
  [109, '2026-09-18', 'unit-control', 'Cling Film Gauge-to-Micron Conversion for Purchase Orders', 'cling-film-gauge-micron-conversion-purchase-order', 'cling film gauge to micron conversion', ['plastic wrap gauge conversion', 'micron mil gauge cling film'], 'informational-to-commercial', 'specification control', 'Convert and record thickness units without changing the agreed physical specification.', 'Import buyers working across metric and U.S. suppliers', 'cling-film-thickness-tolerance-measurement-buyer-guide', 'Solves unit conversion and rounding control; the existing article solves measurement sampling and tolerance.', 'medium', 'Show formulas, rounding rules, worked examples, and the original-unit precedence clause.', 'A procurement desk with a micrometer, clear film sample, metric ruler, imperial ruler, and calculator; no readable numbers.'],
  [110, '2026-09-19', 'usage-cost', 'Cling Film Yield per Cover: Estimate Cost from Real Pan Sizes', 'cling-film-yield-per-cover-pan-size-calculator', 'cling film cost per cover', ['plastic wrap usage calculator', 'commercial cling film yield per roll'], 'commercial investigation', 'cost model', 'Estimate covers per roll and cost per completed cover from pan size, overlap, handling loss, and verified length.', 'Food-service buyers, distributors, and central kitchens', 'cling-film-price-kg-roll-meter-comparison', 'Converts film into a use-level cost per cover; the existing article normalizes supplier quote units.', 'low', 'Include a reproducible formula, waste sensitivity table, and observation-based correction factor.', 'Top-down view of stainless food pans, a clear cling film roll, measuring tape, calculator, and blank worksheet.'],
  [111, '2026-09-20', 'oem-cost', 'OEM Cling Film Cost Breakdown: Film, Core, Cutter, Print, and Carton', 'oem-cling-film-cost-breakdown', 'OEM cling film cost', ['private label cling film price factors', 'custom cling film packaging cost'], 'transactional', 'quote comparison', 'Separate product and packaging cost drivers before comparing OEM quotes.', 'Private-label importers and brand owners', 'cling-film-landed-cost-calculator-importers', 'Breaks down factory/OEM configuration costs before freight; the existing article calculates total landed cost after quote.', 'low', 'Create a quote decomposition table with fixed, variable, and approval-dependent inputs.', 'An OEM cling film sourcing table displaying a clear roll, paper core, cutter box, printing proof, and master carton components.'],
  [112, '2026-09-21', 'trial-strategy', 'Stock Roll vs Custom Cling Film: Choose a Lower-Risk First Order', 'stock-roll-vs-custom-cling-film-first-order', 'stock vs custom cling film', ['low MOQ private label cling film', 'standard cling film roll trial order'], 'transactional', 'trial design', 'Choose which parts of a first order remain standard and which require customization.', 'New importers, distributors, and private-label startups', 'cling-film-moq-lead-time-trial-order-feasibility', 'Builds a standard-versus-custom decision sequence; the existing article explains MOQ and lead-time drivers after configuration.', 'low', 'Use a staged customization ladder and sunk-cost/revision-risk table.', 'A standard unbranded cling film roll and a custom printed cutter box concept arranged as two trial-order paths.'],
  [113, '2026-09-22', 'sample-request', 'Cling Film Sample Request Template for Import Buyers', 'cling-film-sample-request-template-importers', 'cling film sample request', ['request cling film samples from supplier', 'food wrap production sample brief'], 'transactional', 'sample request', 'Request samples that match the intended material, dimensions, core, packaging, lot identity, and test purpose.', 'Importers and distributors preparing supplier trials', 'cling-film-sample-testing-checklist-importers', 'Defines what the supplier must send and identify; the existing article explains how the buyer tests samples after arrival.', 'medium', 'Provide a copyable request email, sample matrix, labeling fields, and representativeness questions.', 'A supplier sample desk with several labeled-by-color cling film rolls, blank sample tags, courier carton, and checklist.'],
  [114, '2026-09-23', 'supplier-audit', 'What a Cling Film Factory Audit Should Verify Before Approval', 'cling-film-factory-audit-checklist', 'cling film factory audit checklist', ['cling film manufacturer audit', 'food wrap supplier factory assessment'], 'commercial investigation', 'supplier approval', 'Verify which production, conversion, inspection, traceability, storage, and subcontracting steps the site controls.', 'Importers, retail brands, and supplier-quality teams', 'cling-film-supplier-china-checklist', 'Goes inside a site-level process audit with evidence trails; the existing article is a broader remote supplier-selection checklist.', 'high', 'Use process mapping and record sampling without claiming YIYUAN owns unverified equipment or certifications.', 'An auditor in a clean cling film production facility reviewing rolls, slitting equipment, inspection bench, and blank records.'],
  [115, '2026-09-24', 'customs-classification', 'Cling Film HS Code: Questions to Resolve Before Customs Classification', 'cling-film-hs-code-customs-classification-questions', 'cling film HS code', ['plastic cling film customs classification', 'PVC PE cling film tariff code'], 'commercial investigation', 'import compliance', 'Build the product facts a customs broker or authority needs before assigning a market-specific tariff code.', 'Cling-film importers, customs teams, and wholesale buyers', 'first-cling-film-import-order-checklist', 'Focuses on product-description evidence and jurisdiction-specific tariff classification; the existing first-order checklist only flags customs and logistics as one part of the order.', 'high', 'Provide a classification input sheet and direct buyers to the destination tariff database, broker, or binding-ruling process rather than publishing a universal code.', 'A customs review desk with clear cling film rolls, neutral tariff folders, material samples, ruler, and magnifier; no flags, codes, or readable text.'],
  [116, '2026-09-25', 'roll-calculation', 'Cling Film Roll Diameter Calculator: Check Equipment and Carton Fit', 'cling-film-roll-diameter-calculator-equipment-fit', 'cling film roll diameter calculator', ['food film roll OD calculation', 'roll length thickness core diameter formula'], 'commercial investigation', 'equipment compatibility', 'Estimate finished roll outside diameter from length, thickness, and core OD, then confirm it with an actual wound sample.', 'Equipment users, converters, private-label buyers, and packaging engineers', 'cling-film-core-size-strength-dispenser-compatibility', 'Provides a reproducible roll-geometry estimate and uncertainty check; the existing article approves core construction and loaded-roll behavior in a dispenser.', 'medium', 'Supply a unit-safe formula, worked examples, winding-factor warning, and physical clearance trial.', 'An engineering bench with a clear food film roll, core, caliper, measuring tape, calculator, and dispenser clearance gauge.'],
  [117, '2026-09-26', 'migration-testing', 'Overall vs Specific Migration Tests for Cling Film: A Buyer Brief', 'cling-film-overall-vs-specific-migration-test-brief', 'cling film migration testing', ['overall migration test cling film', 'specific migration food wrap test'], 'commercial investigation', 'test planning', 'Define the exact film, intended food-contact conditions, jurisdiction, substances, and sample identity before commissioning migration work.', 'Compliance buyers, importers, and private-label teams', 'cling-film-test-reports-buyer-review-before-ordering', 'Selects and scopes migration testing before laboratory work; the existing article teaches buyers how to read a report after it is issued.', 'high', 'Deliver a laboratory brief and result-scope checklist grounded in current official food-contact rules.', 'A laboratory planning scene with clear cling film samples, neutral food simulant glassware, blank test folders, timer, and temperature probe; no seals or readable labels.'],
  [118, '2026-09-27', 'case-pack', 'Cling Film Case Pack: Choose Rolls per Carton for Wholesale Orders', 'cling-film-case-pack-rolls-per-carton-selection', 'cling film rolls per carton', ['commercial cling film case pack', 'food wrap carton quantity'], 'transactional', 'order configuration', 'Choose rolls per inner pack and master carton from channel unit, lifting, cube, compression, receiving, and picking needs.', 'Food-service distributors, wholesalers, and private-label buyers', 'compare-cling-film-quotes-width-length-weight-carton', 'Chooses a channel-ready case-pack structure before quoting; the existing article compares suppliers only after width, length, weight, and carton inputs are already defined.', 'low', 'Provide a sell-unit-to-master-carton decision table and carton approval inputs without inventing a universal pack count.', 'A wholesale packing bench with clear cling film rolls arranged into small and large unbranded carton configurations, plus a blank pick sheet.'],
  [119, '2026-09-28', 'mixed-moq', 'Mixed-SKU Cling Film MOQ: Combine Widths Without Losing Control', 'mixed-sku-cling-film-moq-widths-packaging', 'mixed SKU cling film MOQ', ['combine cling film sizes in one order', 'cling film MOQ multiple widths'], 'transactional', 'order configuration', 'Decide which film, core, box, artwork, and carton inputs can be shared across multiple SKUs.', 'Distributors and private-label brands launching several sizes', 'cling-film-moq-lead-time-trial-order-feasibility', 'Models MOQ interaction across several SKUs; the existing article explains the MOQ of one trial-order configuration.', 'low', 'Use a common-versus-unique component matrix and consolidation decision rules.', 'Several cling film roll widths and neutral cutter boxes grouped into one mixed-SKU order planning layout.'],
  [120, '2026-09-29', 'incoterm', 'FOB vs CIF for Cling Film Imports: Compare Scope, Risk, and Data', 'fob-vs-cif-cling-film-import-quotes', 'FOB vs CIF cling film import', ['cling film FOB price', 'cling film CIF quote comparison'], 'transactional', 'commercial terms', 'Compare supplier quotations on the same port, shipment, insurance, charge, and responsibility basis.', 'First-time importers and wholesale buyers', 'cling-film-landed-cost-calculator-importers', 'Compares two supplier Incoterm quote scopes; the existing worksheet combines all cost layers into landed cost.', 'high', 'Use current ICC terminology, a quote-normalization table, and explicit exclusions instead of legal advice.', 'A shipping desk with clear cling film cartons, port documents, container model, and two neutral quote folders.'],
  [121, '2026-09-30', 'shipment-mode', 'LCL vs FCL for Cling Film Trial Orders: Cost and Damage Decision', 'lcl-vs-fcl-cling-film-trial-order', 'LCL vs FCL cling film shipment', ['cling film trial order shipping', 'food wrap LCL shipment risk'], 'commercial investigation', 'logistics', 'Choose a shipment mode from volume, consolidation handling, timing, damage exposure, and receiving capability.', 'Importers planning trial or growth orders', 'cling-film-ocean-freight-heat-roll-deformation', 'Chooses LCL or FCL before booking; the existing article mitigates heat and movement risk during ocean freight.', 'medium', 'Provide a mode-decision table and identify quote inputs that must come from a forwarder.', 'Export cartons of cling film shown in a shared LCL consolidation area beside a dedicated sealed container loading lane.'],
  [122, '2026-10-01', 'container-size', '20GP vs 40HQ for Cling Film: Build a Loading Comparison', '20gp-vs-40hq-cling-film-loading-comparison', '20GP vs 40HQ cling film loading', ['cling film container loading capacity', 'how many cling film cartons in container'], 'transactional', 'logistics', 'Compare container choices using actual carton dimensions, gross weight, pallet plan, limits, and buffer.', 'Volume importers and distribution buyers', 'cling-film-carton-packing-container-loading-checks', 'Builds a data-driven 20GP-versus-40HQ capacity comparison; the existing article checks carton and loading protection.', 'medium', 'Give formulas and required inputs but never invent universal carton counts.', 'A logistics planning scene with cling film cartons, small 20-foot and tall 40-foot container models, calculator, and blank load plan.'],
  [123, '2026-10-02', 'loading-method', 'Palletized vs Floor-Loaded Cling Film Cartons: Buyer Trade-Offs', 'palletized-vs-floor-loaded-cling-film-cartons', 'palletized vs floor loaded cling film', ['cling film pallet loading', 'floor loaded food wrap cartons'], 'commercial investigation', 'logistics', 'Choose loading method from cube, handling, carton pressure, route, labor, receiving, and claim evidence.', 'Importers, wholesalers, and warehouse managers', 'cling-film-carton-packing-container-loading-checks', 'Compares loading methods and receiving consequences; the existing article gives general carton/loading inspection checks.', 'medium', 'Use a shipper-to-receiver process comparison and require actual pallet/carton validation.', 'Split logistics scene showing cling film cartons neatly palletized on one side and safely floor-loaded in a container on the other.'],
  [124, '2026-10-03', 'load-allocation', 'Mixed-SKU Cling Film Container Loading Without Inventory Imbalance', 'mixed-sku-cling-film-container-loading-allocation', 'mixed SKU cling film container loading', ['combine cling film sizes in container', 'food wrap SKU loading plan'], 'transactional', 'logistics', 'Allocate carton quantities by demand, cube, weight, receiving order, and reorder risk.', 'Cling-film distributors importing several roll sizes', 'cling-film-distributor-sku-assortment-width-length', 'Turns an approved assortment into shipment quantities and loading sequence; the existing article decides which SKUs belong in the portfolio.', 'low', 'Provide allocation constraints and a scenario table without fictional sales numbers.', 'An open shipping container with clearly separated groups of unbranded cling film cartons and color-coded SKU zones without text.'],
  [125, '2026-10-04', 'document-selection', 'COA, COC, DoC, or Test Report: What Cling Film Buyers Need', 'cling-film-coa-coc-doc-test-report-differences', 'cling film COA COC DoC test report', ['cling film compliance documents', 'food wrap certificate of analysis'], 'commercial investigation', 'document review', 'Request the document that answers identity, lot result, conformity, regulatory status, or test-sample questions.', 'Compliance buyers, importers, and private-label brands', 'cling-film-us-eu-food-contact-document-request-checklist', 'Explains document purpose and evidence limits before building a market file; the existing article organizes U.S./EU requests by jurisdiction.', 'high', 'Use an evidence-question matrix and distinguish generic templates from SKU/lot/sample-specific records.', 'A compliance desk with four distinct blank document folders, a clear cling film roll, lot sample, and magnifier; no seals or readable text.'],
  [126, '2026-10-05', 'use-claim', 'Cling Film Use Claims: Match Food, Time, Temperature, and Evidence', 'cling-film-food-time-temperature-use-claims-evidence', 'cling film food contact conditions', ['cling film microwave freezer claims', 'food wrap intended use evidence'], 'commercial investigation', 'claim approval', 'Approve food-contact and use claims only after matching material, SKU, food type, time, temperature, test scope, and market.', 'Private-label brands, compliance teams, and importers', 'cling-film-food-shelf-life-claims-validation', 'Reviews film-use and label claim evidence; the existing article separates packaging from food shelf-life validation.', 'high', 'Create a claim-to-evidence matrix and keep the public PE report limited to its identified sample.', 'A controlled food-contact review setup with clear cling film, cold tray, room-temperature container, timer, thermometer, and blank evidence matrix.'],
]

export const contentPlan = rows.map(([
  number,
  publishDate,
  articleType,
  title,
  slug,
  primaryKeyword,
  longTailKeywords,
  serpIntent,
  funnelStage,
  searchTask,
  targetBuyer,
  nearestExistingPost,
  differentiation,
  evidenceRisk,
  conversionAction,
  coverTheme,
]) => ({
  number,
  publishDate,
  business: 'cling-film',
  articleType,
  title,
  slug,
  primaryKeyword,
  longTailKeywords,
  serpIntent,
  funnelStage,
  searchTask,
  targetBuyer,
  nearestExistingPost,
  differentiation,
  allowedInternalLinks: [...sharedLinks, `/blog/${nearestExistingPost}`],
  sourcePlan: evidenceRisk === 'high'
    ? 'Current official primary sources plus the verified YIYUAN product/PDF scope; re-check at writing time.'
    : 'Verified YIYUAN product/PDF scope and buyer-side calculation or trial logic; no unsupported supplier claims.',
  sourceUrls: officialSources[number] || [],
  evidenceRisk,
  bodyImageCount: 0,
  coverTheme,
  bodyImageThemes: [],
  conversionAction,
}))

export const contentPlanByNumber = new Map(contentPlan.map((item) => [item.number, item]))
export const contentPlanBySlug = new Map(contentPlan.map((item) => [item.slug, item]))

if (contentPlan.length !== batch.expectedArticles) {
  throw new Error(`Expected ${batch.expectedArticles} articles, found ${contentPlan.length}`)
}
